user:
    trans_fname: "data/txs/{}.bin"
    user_pool: "data/user_pool.sql"
    username: "teleplayer123"
    serialized_blocks: "data/blocks.bin"

network:
    host: "0.0.0.0"
    port: 6000 
    shost: "127.0.0.1"
    sport: 6001
    nodes_url: "http://{}:{}/nodes"
    transaction_url: "http://{}:{}/transaction"
    mempool_db: "data/mempool.sql"
    node_db: "data/nodes.sql"
    target_timespan: 1209600
    max_target: 0x00000000ffff0000000000000000000000000000000000000000000000000000
    genesis_bits: 0x1d00ffff
    version: 0x01
    max_difficulty: 8
    max_peers: 5
    max_downtime: 5
    max_transactions: 2
    reward_public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDxoWDq7aRVnfCVuSV7Z0S8sGE59S1suBIT61X4rz/87tk5vJwfAaxwNiS2BrhXXjhglJ5ppH3b6vwCbN4c2h7cJnyHQwyU4asbQOGydqcUrLa+2FWLthzDwzfHqBZPz8q236SyXYeSaBltSY4j58+E5TMfkgnyS1ot+zXiUA3JfwIDAQAB
    reward_private: MIICWwIBAAKBgQDxoWDq7aRVnfCVuSV7Z0S8sGE59S1suBIT61X4rz/87tk5vJwfAaxwNiS2BrhXXjhglJ5ppH3b6vwCbN4c2h7cJnyHQwyU4asbQOGydqcUrLa+2FWLthzDwzfHqBZPz8q236SyXYeSaBltSY4j58+E5TMfkgnyS1ot+zXiUA3JfwIDAQABAoGAX+PDKngUd0WubDyFe2uIA7mbW/zIghSqV+1UuNQTeLTwz9DhxAxN+loCR5pzHXjutqVEGHiG2fdu+ydpHdoR1FaYayvyADQVsZbE22SY8gRdCLt/SAE+orfaoj8vqbroFoLVyrJl9sw4xscyqMTyFq1i66mVIuvd6v6DELYUH0ECQQDyIX2vUmIA/UCWEHuTSW4AmUCDM2/tdHFNZPFAoPZDU4qoATHzLvTeQKUMdPrMhTbpYmD7K7yNyT9CfpvfXwJbAkEA/3iMpQAVXfutWE7KmXXW5AiTblTdVXeKOgDh9jRMIwIQoLiNA0MvWkn861jJb3DGd/sFLeSfaApyf0BMki42rQJAB+6m8m5tfYDOc9wYYEvgia57mZC+0vWknJd4+9gKGUyMV1Kqsz/Pj9RoU88lRDv8/4pUiQX2yGJWazRAoQG4zwJANQWuGyjTRnhP1/4yantcqGNnRgTzEyQGWleIjnL4QmPRU6o6Ci1NjK3Cgo4g8LI1Xv2Ia6gBtbRFY0fTHJve2QJAPXSNHfFFKbVYHlr7R7EGlYCBS9t9e3W4rZjZT00QYRglNEFk5TJo2/291hifg+LqD+qSxS7lNlax5f3WTGIGeQ==
    reward_recipient: "ipaddress"
    status_url: "http://{}:{}/status"
    connect_url: "http://{}:{}/connect"

    